In [1]:
from pyspark.context import SparkContext
from bigdl.util.common import *
sc = get_spark_context(conf=create_spark_conf()) # in case sparkcontext haven't been created.
init_engine()

In [2]:
from bigdl.nn.layer import *
import numpy as np
input = np.array([[0.6653826, 0.25350887, 0.33434764], [0.9618287, 0.5484164, 0.64844745]])
layer = Transpose([(1,2)])
print input
print layer.forward(input)

creating: createTranspose
[[ 0.6653826   0.25350887  0.33434764]
 [ 0.9618287   0.5484164   0.64844745]]
[array([[ 0.66538262,  0.96182871],
       [ 0.25350887,  0.54841638],
       [ 0.33434764,  0.64844745]], dtype=float32)]


In [3]:
module = Threshold(1.0, 0.8)
input = np.random.randn(2, 2, 2)
print input
print module.forward(input)

creating: createThreshold
[[[-0.03433005  1.45572174]
  [-0.78277916  0.12178757]]

 [[ 0.15196584  0.28000754]
  [ 0.49262988 -0.51085725]]]
[array([[[ 0.80000001,  1.45572174],
        [ 0.80000001,  0.80000001]],

       [[ 0.80000001,  0.80000001],
        [ 0.80000001,  0.80000001]]], dtype=float32)]


In [4]:
module = Pack(2)
input1 = np.random.randn(2, 2)
input2 = np.random.randn(2, 2)
input = [input1, input2]

creating: createPack


Py4JError: An error occurred while calling o44.createPack. Trace:
py4j.Py4JException: Method createPack([class java.util.ArrayList, class java.util.ArrayList]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)



In [5]:
module = FlattenTable()
t1 = np.random.randn(3)
t2 = np.random.randn(3)
t3 = np.random.randn(3)
input = [t1, [t2, [t3]]]
module.forward(input)

creating: createFlattenTable


AttributeError: 'list' object has no attribute 'ravel'

In [6]:
module = CosineDistance()
t1 = np.random.randn(3)
t2 = np.random.randn(3)
input = [t1, t2]
print input
module.forward(input)

creating: createCosineDistance
[array([-0.6212963 , -0.79164539, -1.30127964]), array([-0.79718791, -0.38439708, -0.86876813])]


[array([ 0.94608909], dtype=float32)]

In [15]:
from bigdl.nn.criterion import *
module = MultiCriterion()
nll = ClassNLLCriterion()
mse = MSECriterion()
module.add(nll, 0.5)
module.add(mse)

input = np.array([0.9682213801388531,
0.35258855644097503,
0.04584479998452568,
-0.21781499692588918,
-1.02721844006879])
target = np.array([1, 2, 3, 2, 1])
module.forward(input, target)

creating: createMultiCriterion
creating: createClassNLLCriterion
creating: createMSECriterion


3.6099546

In [11]:
criterion = MultiLabelSoftMarginCriterion()
input = np.array([0.4, 0.5, 0.6])
target = np.array([0, 1, 1])

criterion.forward(input, target)

creating: createMultiLabelSoftMarginCriterion


0.6081934

In [12]:
module = PReLU(2)
input = np.random.randn(2, 2, 3)
print input
module.forward(input)

creating: createPReLU
[[[ 0.06738404  1.4002115  -0.5472932 ]
  [-0.09001043 -0.44532665  0.01354737]]

 [[ 0.35791868  0.13271149  0.80973177]
  [ 1.23492742 -0.01768156  0.68465583]]]


[array([[[ 0.06738404,  1.40021145, -0.1368233 ],
         [-0.02250261, -0.11133166,  0.01354737]],
 
        [[ 0.35791868,  0.13271149,  0.80973178],
         [ 1.23492742, -0.00442039,  0.68465585]]], dtype=float32)]

In [10]:
hiddenSize = 4
inputSize = 5
module = Recurrent().add(RnnCell(inputSize, hiddenSize, Tanh()))
input = np.zeros((1, 5, 5))
input[0][0][4] = 1
input[0][1][0] = 1
input[0][2][4] = 1
input[0][3][3] = 1
input[0][4][0] = 1
module.forward(input)

creating: createRecurrent
creating: createTanh
creating: createRnnCell


[array([[[ 0.298565  , -0.09832189, -0.55038035,  0.20554446],
         [-0.20272326, -0.02060957, -0.01023044,  0.12978098],
         [ 0.19904721, -0.18201435, -0.48911813,  0.20552115],
         [ 0.12379841,  0.16622475, -0.16854623,  0.05604605],
         [-0.04976237, -0.25355211, -0.22811897, -0.28813571]]], dtype=float32)]